version: "3.8"
services:
  python-learn-bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    image: seemann-learn-bot
    container_name: seemann_learn_bot
    restart: always
